alter table public.projects add column if not exists slug text;
alter table public.projects add column if not exists title text not null default 'Untitled Project';
alter table public.projects add column if not exists teaser_title text not null default 'Coming Soon';
alter table public.projects add column if not exists tagline text not null default '';
alter table public.projects add column if not exists teaser_tagline text not null default '';
alter table public.projects add column if not exists summary text not null default '';
alter table public.projects add column if not exists teaser_summary text not null default '';
alter table public.projects add column if not exists description text not null default '';
alter table public.projects add column if not exists teaser_description text not null default '';
alter table public.projects add column if not exists status text not null default 'In Development';
alter table public.projects add column if not exists project_type text not null default 'Film';
alter table public.projects add column if not exists poster_url text not null default '';
alter table public.projects add column if not exists teaser_poster_url text not null default '';
alter table public.projects add column if not exists actors text not null default '';
alter table public.projects add column if not exists teaser_actors text not null default '';
alter table public.projects add column if not exists production_company text not null default '';
alter table public.projects add column if not exists teaser_production_company text not null default '';
alter table public.projects add column if not exists credits jsonb not null default '[]'::jsonb;
alter table public.projects add column if not exists teaser_credits text not null default '';
alter table public.projects add column if not exists tags text[] not null default '{}';
alter table public.projects add column if not exists theme text not null default 'orange';
alter table public.projects add column if not exists reveal_states jsonb not null default '{}'::jsonb;
alter table public.projects add column if not exists is_published boolean not null default false;
alter table public.projects add column if not exists is_featured boolean not null default false;
alter table public.projects add column if not exists created_at timestamptz not null default now();
alter table public.projects add column if not exists updated_at timestamptz not null default now();
create unique index if not exists projects_slug_unique on public.projects (slug);
create unique index if not exists one_featured_project on public.projects (is_featured) where is_featured = true;
select 'project columns created successfully' as result;
